# Generated by Django 4.2.3 on 2023-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('banco', models.CharField(choices=[('NU', 'Nubank'), ('CCF', 'Caixa Economica Federal'), ('BR', 'Bradesco'), ('BB', 'Banco do Brasil'), ('BAN', 'Banrisul'), ('IT', 'Itau'), ('UN', 'Unicred'), ('AGI', 'Agibank'), ('ST', 'Santander'), ('SI', 'Sicredi')], max_length=3)),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], max_length=2)),
                ('valor', models.FloatField()),
                ('icone', models.ImageField(upload_to='icones')),
            ],
        ),
    ]
